apiVersion: 1

datasources:
- name: Metrics
  type: prometheus
  access: proxy
  url: https://internal.kodmain.run/prometheus
  jsonData:
    tlsSkipVerify: true

- name: CloudWatch
  type: cloudwatch
  jsonData:
    authType: default
    defaultRegion: 'eu-west-3'