global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'node-exporter'
    scheme: https
    metrics_path: '/node-exporter/metrics'
    static_configs:
      - targets: ['internal.kodmain.run']
    tls_config:
      insecure_skip_verify: true