apiVersion: 1

dashboards:
  providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    editable: true
    options:
      path: /etc/grafana/provisioning/dashboards/mixed.json
      foldersFromFilesStructure: false

datasources:
- name: Metrics
  type: prometheus
  access: proxy
  url: http://internal.kodmain.run/prometheus
- name: CloudWatch
  type: cloudwatch
  jsonData:
    authType: default
    defaultRegion: 'eu-west-3'