host: localhost
info:
  contact: {}
  description: TheTipTop API
  title: TheTipTop
  version: dev
paths:
  /recover/password:
    post:
      consumes:
      - multipart/form-data
      operationId: client.PasswordRecover
      parameters:
      - default: user-thetiptop@yopmail.com
        description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Password recover
        "400":
          description: Invalid email
        "404":
          description: Client not found
        "500":
          description: Internal server error
      tags:
      - Recover
  /recover/validation:
    post:
      consumes:
      - multipart/form-data
      operationId: client.ValidationRecover
      parameters:
      - default: user-thetiptop@yopmail.com
        description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - description: Type of validation
        enum:
        - mail
        - password
        - phone
        in: formData
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      tags:
      - Recover
  /status/healthcheck:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      operationId: status.HealthCheck
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Show the status of server.
      tags:
      - Status
  /status/ip:
    get:
      consumes:
      - '*/*'
      description: get the ip of user.
      operationId: status.IP
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show the ip of user.
      tags:
      - Status
  /user/auth:
    post:
      consumes:
      - multipart/form-data
      operationId: client.SignIn
      parameters:
      - default: user-thetiptop@yopmail.com
        description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - default: Aa1@azetyuiop
        description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Client signed in
        "400":
          description: Invalid email or password
        "500":
          description: Internal server error
      tags:
      - User
  /user/auth/renew:
    get:
      consumes:
      - '*/*'
      - multipart/form-data
      operationId: client.SignRenew
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: JWT token renewed
        "400":
          description: Invalid token
        "401":
          description: Token expired
        "500":
          description: Internal server error
      tags:
      - User
  /user/password/update:
    put:
      consumes:
      - multipart/form-data
      operationId: client.PasswordUpdate
      parameters:
      - default: user-thetiptop@yopmail.com
        description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - default: Aa1@azetyuiop
        description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Token
        in: formData
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Password updated
        "400":
          description: Invalid email, password or token
        "404":
          description: Client not found
        "409":
          description: Client already validated
        "410":
          description: Token expired
        "500":
          description: Internal server error
      tags:
      - User
  /user/register:
    post:
      consumes:
      - multipart/form-data
      operationId: client.SignUp
      parameters:
      - default: user-thetiptop@yopmail.com
        description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - default: Aa1@azetyuiop
        description: Password
        in: formData
        name: password
        required: true
        type: string
      - default: true
        description: CGU
        in: formData
        name: cgu
        required: true
        type: boolean
      - default: false
        description: Newsletter
        in: formData
        name: newsletter
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "201":
          description: Client created
        "400":
          description: Invalid email or password
        "409":
          description: Client already exists
        "500":
          description: Internal server error
      tags:
      - User
  /user/register/validation:
    put:
      consumes:
      - multipart/form-data
      operationId: client.SignValidation
      parameters:
      - description: Token
        in: formData
        name: token
        required: true
        type: string
      - default: user-thetiptop@yopmail.com
        description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Client email validate
        "400":
          description: Invalid email or token
        "404":
          description: Client not found
        "409":
          description: Client already validated
        "410":
          description: Token expired
        "500":
          description: Internal server error
      tags:
      - User
swagger: "2.0"
