host: localhost
info:
  contact: {}
  description: TheTipTop API
  title: TheTipTop
  version: dev
paths:
  /password/recover:
    post:
      consumes:
      - '*/*'
      operationId: client.PasswordRecover
      parameters:
      - description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Password recover
        "400":
          description: Invalid email
        "404":
          description: Client not found
        "500":
          description: Internal server error
      tags:
      - Password
  /password/update:
    put:
      consumes:
      - '*/*'
      operationId: client.PasswordUpdate
      parameters:
      - description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Token
        in: formData
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Password updated
        "400":
          description: Invalid email, password or token
        "404":
          description: Client not found
        "409":
          description: Client already validated
        "410":
          description: Token expired
        "500":
          description: Internal server error
      tags:
      - Password
  /sign/in:
    post:
      consumes:
      - '*/*'
      operationId: client.SignIn
      parameters:
      - description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Client signed in
        "400":
          description: Invalid email or password
        "500":
          description: Internal server error
      tags:
      - Sign
  /sign/renew:
    get:
      consumes:
      - '*/*'
      operationId: client.SignRenew
      produces:
      - application/json
      responses:
        "200":
          description: JWT token renewed
        "400":
          description: Invalid token
        "401":
          description: Token expired
        "500":
          description: Internal server error
      tags:
      - Sign
  /sign/up:
    post:
      consumes:
      - multipart/form-data
      operationId: client.SignUp
      parameters:
      - description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Client created
        "400":
          description: Invalid email or password
        "409":
          description: Client already exists
        "500":
          description: Internal server error
      tags:
      - Sign
  /sign/validation:
    put:
      consumes:
      - '*/*'
      operationId: client.SignValidation
      parameters:
      - description: Token
        in: formData
        name: token
        required: true
        type: string
      - description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Client email validate
        "400":
          description: Invalid email or token
        "404":
          description: Client not found
        "409":
          description: Client already validated
        "410":
          description: Token expired
        "500":
          description: Internal server error
      tags:
      - Sign
  /status/healthcheck:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      operationId: status.HealthCheck
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Show the status of server.
      tags:
      - Status
  /status/ip:
    get:
      consumes:
      - '*/*'
      description: get the ip of user.
      operationId: status.IP
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show the ip of user.
      tags:
      - Status
swagger: "2.0"
