host: localhost
info:
  contact: {}
  description: TheTipTop API
  title: TheTipTop
  version: dev
paths:
  /password/recover:
    post:
      consumes:
      - '*/*'
      operationId: client.PasswordRecover
      parameters:
      - description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      tags:
      - Password
  /sign/in:
    post:
      consumes:
      - '*/*'
      operationId: client.SignIn
      parameters:
      - description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - Sign
  /sign/renew:
    get:
      consumes:
      - '*/*'
      operationId: client.SignRenew
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      tags:
      - Sign
  /sign/up:
    post:
      consumes:
      - multipart/form-data
      operationId: client.SignUp
      parameters:
      - description: Email address
        format: email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Client created
        "400":
          description: Client already exists
      tags:
      - Sign
  /status/healthcheck:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      operationId: status.HealthCheck
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Show the status of server.
      tags:
      - Status
  /status/ip:
    get:
      consumes:
      - '*/*'
      description: get the ip of user.
      operationId: status.IP
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show the ip of user.
      tags:
      - Status
  /validation/:id/:token:
    get:
      consumes:
      - '*/*'
      operationId: client.ValidationMail
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Sign
swagger: "2.0"
