info:
  contact: {}
paths:
  /client:
    delete:
      consumes:
      - '*/*'
      operationId: client.Delete
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Models
    get:
      consumes:
      - '*/*'
      operationId: client.Find
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Models
    patch:
      consumes:
      - '*/*'
      operationId: client.UpdatePartial
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Models
    put:
      consumes:
      - '*/*'
      operationId: client.UpdateComplete
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Models
  /client/:id:
    get:
      consumes:
      - '*/*'
      operationId: client.FindOne
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Models
  /client/password/renew:
    post:
      consumes:
      - '*/*'
      operationId: client.Renew
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Password
  /client/password/reset:
    post:
      consumes:
      - '*/*'
      operationId: client.Reset
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Password
  /sign/in:
    post:
      consumes:
      - '*/*'
      operationId: client.SignIn
      parameters:
      - description: Email address
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Sign
  /sign/out:
    get:
      consumes:
      - '*/*'
      operationId: client.SignOut
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Sign
  /sign/up:
    post:
      consumes:
      - multipart/form-data
      operationId: client.SignUp
      parameters:
      - description: Email address
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - Sign
  /status/healthcheck:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      operationId: status.HealthCheck
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Show the status of server.
      tags:
      - Status
  /status/ip:
    get:
      consumes:
      - '*/*'
      description: get the ip of user.
      operationId: status.IP
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show the ip of user.
      tags:
      - Status
swagger: "2.0"
