global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nomad'
    metrics_path: '/v1/metrics'
    scheme: https
    params:
        format: ['prometheus']
    static_configs:
      - targets: ['nomad.kodmain.run']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter.kodmain.run']