global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    nomad: ${NOMAD_HOST_ADDR_nomad}
    node: ${NOMAD_HOST_ADDR_node-exporter}

scrape_configs:
  - job_name: 'nomad'
    metrics_path: '/v1/metrics'
    scheme: https
    params:
        format: ['prometheus']
    static_configs:
      - targets: ['dummy_nomad:1234'] # Cible fictive
    relabel_configs:
      - source_labels: [__address__, nomad]
        regex: 'dummy_nomad:1234;(.*)'
        target_label: __address__
        replacement: '${1}'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['dummy_node:1234'] # Cible fictive
    relabel_configs:
      - source_labels: [__address__, node]
        regex: 'dummy_node:1234;(.*)'
        target_label: __address__
        replacement: '${1}'
