global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    nomad: ${NOMAD_HOST_ADDR_nomad}
    node: ${NOMAD_HOST_ADDR_node-exporter}

scrape_configs:
  - job_name: 'nomad'
    metrics_path: '/v1/metrics'
    scheme: https
    params:
        format: ['prometheus']
    static_configs:
      - targets: 
        - ${nomad}
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - ${node}