info:
  contact: {}
paths:
  /status/healthcheck:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      operationId: status.HealthCheck
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Show the status of server.
      tags:
      - Status
  /status/ip:
    get:
      consumes:
      - '*/*'
      description: get the ip of user.
      operationId: status.IP
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show the ip of user.
      tags:
      - Status
swagger: "2.0"
