definitions:
  model.User:
    description: User account information with user id and username
    properties:
      cgu:
        type: boolean
      createdAt:
        type: integer
      email:
        type: string
      id:
        type: string
      newsletter:
        type: boolean
      password:
        type: string
      updatedAt:
        type: integer
    type: object
info:
  contact: {}
paths:
  /status/healthcheck:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      operationId: status.HealthCheck
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Show the status of server.
      tags:
      - Status
  /status/ip:
    get:
      consumes:
      - '*/*'
      description: get the ip of user.
      operationId: status.IP
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show the ip of user.
      tags:
      - Status
  /user/auth:
    post:
      consumes:
      - '*/*'
      description: Auth user in the system.
      operationId: user.Auth
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Show the user auth action.
      tags:
      - User
  /user/register:
    post:
      consumes:
      - '*/*'
      description: Register a new user in the system.
      operationId: user.Register
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Show the user register action.
      tags:
      - User
swagger: "2.0"
