services:
  client:
    database: default
    mail: default
  employee:
    database: default
    mail: default

providers:
  mails:
    default:
      username: secret
      password: secret
      host: localhost
      port: 1025
      expeditor: Whoami
      from: whoami@localhost

  databases:
    file:
      protocol: sqlite
      dbname: ${PWD}/db.sqlite
      logger: true
    default:
      protocol: sqlite
      dbname: ':memory:'
      logger: true

security:
  validation:
    expire: 30m
  jwt:
    tz: Europe/Paris
    secret: secret
    expire: 15
    refresh: 30