services:
  client:
    database: default
    mail: default
  employee:
    database: default
    mail: default

providers:
  mails:
    default:
      username: secret
      password: secret
      host: localhost
      port: 1025
      expeditor: Whoami
      from: whoami@localhost

  databases:
    file:
      protocol: sqlite
      dbname: ${PWD}/db.sqlite #uncomment this line to use a file 
      logger: true
    default:
      protocol: sqlite
      dbname: ':memory:' # we need memory for test
      logger: true

security:
  validation:
    expire: 30m
  jwt:
    #tz: Europe/Paris
    secret: secret
    expire: 15
    refresh: 30