services:
  client:
    database: default

providers:
  mails:
    default:
      username: secret 
      password: secret
      host: localhost
      port: 1025
      expeditor: Whoami
      from: whoami@localhost
    
  databases:
    default:
      protocol: sqlite
      dbname: ':memory:' # we need memory for test
      #dbname: ${PWD}/../.build/db.sqlite #uncomment this line to use a file 

security:
  validation:
    expire: 30m
  jwt: 
    #tz: Europe/Paris
    secret: secret
    expire: 15
    refresh: 30