services:
  client:
    database: default

providers:
  mails:
    default:
      username: secret 
      password: secret
      host: localhost
      port: 1025
      expeditor: Whoami
      from: whoami@localhost
    
  databases:
    default:
      protocol: sqlite
      dbname: ':memory:'

security:
  validation:
    expire: 1m
  jwt: 
    #tz: Europe/Paris
    secret: secret
    expire: 15
    refresh: 30