mail:
  username: secret
  password: secret
  host: smtp.world.com
  port: 0
  expeditor: Whoami
  from: hello@world.com
  disable: true

databases:
  default:
    protocol: sqlite
    dbname: ':memory:'

jwt: 
  #tz: Europe/Paris
  secret: secret
  expire: 15
  refresh: 30
