name: CI

on:
  push:
    branches:
      - update/workflow
  pull_request:
    branches:
      - update/workflow
    
permissions:
  pull-requests: write
  contents: write
  packages: write

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache-dependency-path: api/go.sum

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.19.5

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flutter dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Upload project to Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: project
          path: .

  Build:
    name: Build
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Download project from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: project
          path: .

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build Image ARM64
        uses: docker/build-push-action@v5
        with:
          file: .github/dockerfiles/builder.Dockerfile
          context: .
          push: true
          platforms: linux/arm64
          build-args: |
            BINARY_VERSION=test
          tags: ghcr.io/${{ github.repository }}:PREVIEW-arm64
      
      - name: Build Image AMD64
        uses: docker/build-push-action@v5
        with:
          file: .github/dockerfiles/builder.Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          build-args: |
            BINARY_VERSION=test
          tags: ghcr.io/${{ github.repository }}:PREVIEW-amd64

      - name: Extract release from build
        run: task extract "IMAGE_TAG=ghcr.io/${{ github.repository }}:PREVIEW-arm64" && task extract "IMAGE_TAG=ghcr.io/${{ github.repository }}:PREVIEW-amd64" 

      - name: Upload project to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artefacts
          path: ./artefacts.zip