name: CI

on:
  push:
    branches:
      - update/workflow
  pull_request:
    branches:
      - update/workflow
    
permissions:
  pull-requests: write
  contents: write
  packages: write

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache-dependency-path: api/go.sum

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.19.5

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup dependencies
        run: go install gotest.tools/gotestsum@latest

      - name: Setup Flutter dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Upload project to Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: project
          path: .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Download project from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: project
          path: .

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the app
        run: task api:build:cross
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          PATH: $HOME/go/bin:/usr/local/go/bin:$PATH

      - name: Upload built binaries to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.goos }}-${{ matrix.goarch }}
          path: .build/api/project-${{ matrix.goos }}-${{ matrix.goarch }}