name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: 1.11.0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run all the tests and code checks
        run:  make test units
