name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
              
      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest


      - name: Run all the tests and code checks
        run:  make test units
