name: CI

on:
  pull_request:
  push:
    tags:
      - '*'

permissions:
  pull-requests: read
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run all the tests and code checks
        run: make test units

      - name: Upload coverage to Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: go-coverage
          path: .

  sonarcloud:
    name: SonarCloud
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: go-coverage
          path: .

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=kodmain_thetiptop
            -Dsonar.organization=kodmain
            -Dsonar.go.coverage.reportPaths=coverage.out
